[project]
name = "mlops-pipeline"
version  = "0.0.1"
description = "Production grade MLOps pipeline for CNN Classification"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    {name="Sarvesh Kohad"}
]
dynamic = ["dependencies"]

[tool.setuptools.packages.find]
where = ['.']
include = ['src*']
